language: rust
sudo: false

cache:
  directories:
    - /home/travis/.cargo

GH_TOKEN: &GH_TOKEN

DEPLOY_TO_GITHUB: &DEPLOY_TO_GITHUB
  before_deploy:
    - git config --local user.name "NoahKinslow"
    - git config --local user.email "39603201+NoahKinslow@users.noreply.github.com"
    - name="git_switch_user_cli-$TRAVIS_TAG-$TARGET"
    - mkdir $name
    - cp target/$TARGET/release/git_switch_user_cli $name/
    - cp README.md LICENSE-MIT LICENSE-APACHE $name/
    - tar czvf $name.tar.gz $name
  deploy:
    provider: releases
    api_key: *GH_TOKEN
    file: git_switch_user_cli-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      branch: master
      tags: true


matrix:
include:
  
  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: nightly
    before_script: rustup target add $TARGET
    script: cargo build --release --target $TARGET --locked --features vendored-openssl
    addons:
      apt:
        packages:
          - musl-tools
    <<: *DEPLOY_TO_GITHUB

  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: nightly
    before_script: rustup target add $TARGET
    script: cargo build --release --target $TARGET --locked --features vendored-openssl
    addons:
      apt:
        packages:
          - musl-tools
    <<: *DEPLOY_TO_GITHUB

  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
    script: cargo build --release --target $TARGET --locked
    install: true
    <<: *DEPLOY_TO_GITHUB